# Default keymaps aggregator - collects all keymap sections
let
  # List all keymap modules (order matters)
  keymapModules = [
    "general"
    "lsp"
    "bufferline"
    "mason"
    "conform"
    "flash"
    "grug-far"
    "noice"
    "persistence"
    "snacks"
    "todo-comments"
    "trouble"
    "which-key"
    "mini-surround"
    "neogen"
    "dap-core"
    "dap-ui"
    "aerial"
    "telescope-extra"
    "dial"
    "vim-illuminate"
    "leap"
    "mini-surround-extra"
    "mini-diff"
    "mini-files"
    "outline"
    "overseer"
    "refactoring"
    "ansible"
    "markdown"
    "python-dap"
    "python-venv"
    "sql"
    "tex"
    "snacks-explorer"
    "snacks-picker"
    "todo-comments-snacks"
    "neotest"
    "neotest-dap"
    "edgy"
    "chezmoi"
    "gitui"
    "octo"
    "project"
    "kulala"
    "adoboards"
  ];
  
  # Import and concatenate all modules
  importModule = name: import ./${name}.nix;
in
  builtins.concatLists (map importModule keymapModules)